{
  "openapi": "3.1.1",
  "info": {
    "title": "The Session API for the Geoprise GM-X Auto Enteprise Resources Planning (ERP) Application",
    "summary": "The GM-X Session manager",	
    "description": "The Session API provides persistent programmatic access, valid until a subsequent logoff action, to the Geoprise GM-X Auto ERP Application by setting a PHP session cookie after successful Internal, RADIUS, LDAP, or SSL authentication.",
    "termsOfService": "https://geoprise.com/termsfeed/terms-and-conditions/",	
    "contact": {
      "name": "GM-X Auto Support",
      "url": "https://geoprise.com/contact-us/",
      "email": "support@geoprise.com"	  
    },
    "version": "11.3.0"	
  },
  "servers": [
    {
      "url": "https://system.api.example.com/gmx/menu",
      "description": "Production server for live traffic using internal, RADIUS, LDAP or SSL authentication"
    },
    {
      "url": "https://api.example.com/gmx/menu",
      "description": "Production server for live traffic using AWS ALB authentication"
    },
    {
      "url": "https://staging-api.example.com/gmx/menu",
      "description": "Staging environment for final checks using internal, RADIUS, LDAP or SSL authentication"
    },	
    {
      "url": "https://qa-api.example.com/gmx/menu",
      "description": "Test environment using internal, RADIUS, LDAP or SSL authentication"
    },
    {
      "url": "http://localhost:3000/gmx/menu",
      "description": "Local development server using internal, RADIUS, LDAP or SSL authentication"
    }	
  ],
  "tags": [
    {
      "name": "Sessions"
    }
  ],  
  "paths": {
    "/logon.php": {
      "get": {
        "summary": "Persistent logon request",
        "description": "Request logon to the Geoprise GM-X Auto ERP Application using Internal, RADIUS, LDAP, or SSL authentication.",
        "operationId": "logonRequest",
        "parameters": [
          {
            "name": "action",
            "in": "query",
            "required": false,			
            "description": "Action to activate Retrieve User Password task.",
            "schema" : {
              "type": "string",
              "@value": "recoverpswd"
            }
          },
          "oneOf": [
            {
              "name": "email_addr",
              "in": "query",
              "required": false,			
              "description": "Email address of user for bypassing the Logon form if this GM-X instance is configured to use Email Address as the Login Type.",
              "schema" : {
                "type": "string",
                "maxLength": 50,
                "pattern": "/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/"
              }
            },
            {
              "name": "user_id",
              "in": "query",
              "required": false,				
              "description": "Internal user identifier for bypassing the Logon form if this GM-X instance is configured to use User Id as the Login Type.",
              "schema" : {
                "type": "string",
                "maxLength": 16,
                "pattern": "^[A-Z0-9\\W]{1,16}$"
              }
            }
          ],
          {
            "$ref": "#/components/parameters/session_name"	
          },
          {
            "name": "user_password",
            "in": "query",
            "required": false,				
            "description": "Internal user password for bypassing the Logon form.",
            "schema" : {
              "type": "string",
              "minLength": 1,
              "maxLength": 16,
              "pattern": "^[A-Za-z0-9\\W_]{1,16}$"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response containing the Logon form or Geoprise GM-X Auto Application Manifest.",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "type": "array",
                      "required": [
                        "logon",
                        "actbar",						
                        "params"		  
                      ],					  
                      "items": {
                        "logon": {
                          "oneOf": [
                            {						  
                              "email_addr": {
                                "type": "string",								  
                                "size": "50",
                                "required": "y"
                              }
						    },
                            {						  
                              "user_id": {
                                "type": "string",								  
                                "size": "16",
                                "required": "y"
                              }
						    }							
						  ],
                          "user_password": {
                            "type": "string",								  
                            "size": "16",
                            "required": "y"
                          }
                        },
                        "actbar": {
                          "button": {
                            "submitLogin": {
                              "type": "string",			    
                              "description": "Enter the system using these credentials",
                              "pattern": "^LOGIN$"
                            }		
                          }
                        },
                        "infomsg": {
                          "line": "Your password has been e-mailed"
                        },
                        "params": {
                          "script": {
                            "$ref": "#/components/schemas/ScriptURL"							
                          },
                          "session_name": {
                            "$ref": "#/components/schemas/session_name"							
                          },
                          "csrf_id": {
                            "$ref": "#/components/schemas/csrf_id"							
                          },
                          "title": "Logon Screen",
                          "version": "GM-X v11.3.0",
                          "language": "en",
                          "project_code": {
                            "$ref": "#/components/schemas/ProjectCode"							
                          },
                          "image-dir": "../images/",
                          "mode": "logon",
                          "taskid": "logon"
                        }
                      }
                    },
                    {
                      "$ref": "#/paths/~1mnu_user(upd1)c.php/get/responses/200/content/application~1json/schema/items"
                    },					
                    {
                      "description": "A successful response containing the Home Page.",
                      "content": {
                        "text/html": {
                          "schema": {
                            "type": "string",
                            "description": "The raw HTML content of the page containing the Help text"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Persistent logon submission",
        "description": "Logon to the Geoprise GM-X Auto ERP Application using Internal, RADIUS, LDAP, or SSL authentication.",
        "operationId": "logon",		  
        "requestBody": {
          "description": "User credentials and other information needed to log on to the Geoprise GM-X Auto ERP Application",
          "required": "true",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "oneOf": [
				    {
                      "email_addr",						
                      "user_id"
                    }					  
                  ],
                  "user_password",				  
                  "session_name",
                  "csrf_id",
                  "submitLogin"				  
                ],
                "properties": {
                  "email_addr": {
                    "type": "string",
                    "description": "Email address of user if this GM-X instance is configured to use Email Address as the Login Type.",
                    "maxLength": 50,
                    "pattern": "/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/",			
                    "example": "derek.lee@worldwideuniversalcorporation.com"
                  },
                  "user_id": {
                    "type": "string",
                    "description": "Internal user identifier if this GM-X instance is configured to use User Id as the Login Type.",
                    "maxLength": 16,
                    "pattern": "^[A-Z0-9\\W]{1,16}$",			
                    "example": "DLEE"
                  },
                  "user_password": {
                    "type": "string",
                    "description": "Internal user password.",
                    "minLength": 1,					
                    "maxLength": 16,
                    "pattern": "^[A-Za-z0-9\\W_]{1,16}$",			
                    "example": "Ar1x?uXdoD05i9Tg"
                  },				  
                  "session_name": {
                    "$ref": "#/components/schemas/session_name"
                  },
                  "csrf_id": {
                    "$ref": "#/components/schemas/csrf_id"
                  },
                  "submitLogin": {
                    "$ref": "#/components/schemas/submitLogin"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "A failure response, or a successful response containing the Geoprise GM-X Auto Application Manifest.",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "type": "array",
                      "required": [
                        "logon",
                        "actbar",						
                        "params"		  
                      ],
                      "items": {
                        "logon": {
                          "allOf": [
                            {
                              "oneOf": [
                                {						  
                                  "email_addr": {
                                    "type": "string",								  
                                    "size": "50",
                                    "required": "y"
                                  }
                                },
                                {						  
                                  "email_addr": {
                                    "type": "string",								  
                                    "size": "50",
                                    "required": "y"
                                  }
                                },	
                                {						  
                                  "user_id": {
                                    "type": "string",								  
                                    "size": "16",
                                    "required": "y"
                                  }
                                },							
                                {						  
                                  "user_id": {
                                    "type": "string",								  
                                    "size": "16",
                                    "required": "y"
                                  }
                                }							
                              ],
                            },
                            {
                              "oneOf": [
                                {						  
                                  "user_password": {
                                    "type": "string",								  
                                    "size": "16",
                                    "required": "y"
                                  }
                                },
                                {						  
                                  "user_password": {
                                    "type": "string",								  
                                    "size": "16",
                                    "required": "y",
                                    "error": "user_password cannot be blank."									
                                  }
                                }
                              ]
                            }
                          ]
                        },
                        "actbar": {
                          "$ref": "#/paths/~1logon.php/get/responses/200/content/application~1json/schema/items/actbar"
                        },
                        "errmsg": {
                          "line": "Security violation."
                        },						
                        "params": {
                          "$ref": "#/paths/~1logon.php/get/responses/200/content/application~1json/schema/items/params"
                        }
                      }
                    },
                    {
                      "description": "A successful response containing the Application Manifest.",
                      "content": {
                        "text/html": {
                          "schema": {
                            "type": "string",
                            "required": [
                              "mnu_favourite",
                              "mnu_dashboard",
                              "mnu_todo",
                              "wf_workitem_role",
                              "wf_workitem_user",
                              "menubar", 
                              "navbar", 
                              "pagination", 
                              "params" 
                            ],
                            "items": {               
                              "$ref": "./GMXAuto_menu.json#/get/responses/200/content/application~1json/schema/items"
                            }
                          }
                        }
                      }
                    }
                  ]
                }			
              }
            }
          }
        }
      }
    },
    "/mnu_user(upd1)c.php": {
      "get": {
        "summary": "Request to retrieve user password",
        "description": "Request internal user password.",
        "operationId": "retrievePasswordRequest",
        "parameters": [
          {
            "$ref": "#/components/parameters/csrf_id"	
          },		
          {
            "$ref": "#/components/parameters/session_name"		
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response containing the Retrieve User Password form.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "required": [
                    "mnu_user",
                    "actbar",
                    "scrolling",
                    "infomsg",					
                    "params"		  
                  ],					  
                  "items": {
                    "mnu_user": {
                      "email_addr": {
                        "type": "string",								  
                        "size": "50"
                      }
                    },
                    "actbar": {
                      "button": [
                        "submitLogin": {
                          "type": "string",			    
                          "description": "Enter the system using these credentials",
                          "pattern": "^LOGIN$"
                        },
                        "quit": {
                          "type": "string",			    
                          "description": "Returns to previous screen",
                          "pattern": "^CANCEL$"
                        }
                      ]
                    },
                    "scrolling": {
                      "scroll": {
                        "mnu_user": {
                          "curitem": {
                            "type": "string",							  
							"pattern": "^1$"
                          },
                          "lastitem": {
                            "type": "string",							  
							"pattern": "^1$"
                          }
                        }
                      }
                    },
                    "infomsg": {
                      "line": "Enter e-mail address where password is to be sent"
                    },
                    "params": {
                      "script": {
                        "$ref": "#/components/schemas/ScriptURL"							
                      },
                      "script_short": "mnu_user_upd1_c",
                      "session_name": {
                        "$ref": "#/components/schemas/session_name"							
                      },
                      "csrf_id": {
                        "$ref": "#/components/schemas/csrf_id"							
                      },
                      "title": "Retrieve User Password",
                      "version": "GM-X v11.3.0",
                      "language": "en",
                      "project_code": {
                        "$ref": "#/components/schemas/ProjectCode"							
                      },
                      "image-dir": "../images/",
                      "mode": "recover",
                      "taskid": "mnu_user(upd1)c"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Password request submission",
        "description": "Submit internal user password request.",
        "operationId": "submitPasswordRequest",		
        "requestBody": {
          "description": "User email address and other information needed to retrieve internal user password",
          "required": "true",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email_addr",				  
                  "session_name",
                  "csrf_id",
                  "oneOf": [
				    {
                      "submitBtn",						
                      "quit"
                    }					  
                  ]				  
                ],
                "properties": {
                  "email_addr": {
                    "type": "string",
                    "description": "Email address of user.",
                    "maxLength": 50,
                    "pattern": "/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/",			
                    "example": "derek.lee@worldwideuniversalcorporation.com"
                  },
                  "session_name": {
                    "$ref": "#/components/schemas/session_name"
                  },
                  "csrf_id": {
                    "$ref": "#/components/schemas/csrf_id"
                  },
                  "submitBtn": {
                    "$ref": "#/components/schemas/submitBtn"
                  },
                  "quit": {
                    "$ref": "#/components/schemas/quitCancel"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "A failure response, or a successful response containing the Geoprise GM-X Auto Logon form.",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "type": "array",
                      "required": [
                        "mnu_user",
                        "actbar",						
                        "params"		  
                      ],
                      "items": {
                        "mnu_user": {
                          "oneOf": [
                            {						  
                              "email_addr": {
                                "type": "string",								  
                                "size": "50",
                                "required": "y"
                              }
                            },
                            {						  
                              "email_addr": {
                                "type": "string",								  
                                "size": "50",
                                "required": "y",
                                "error": "email_addr cannot be blank."
                              }
                            }							
                          ]
                        },
                        "actbar": {
                          "$ref": "#/paths/~1mnu_user(upd1)c.php/get/responses/200/content/application~1json/schema/items/actbar"
                        },
                        "errmsg": {
                          "line": "E-mail address was not found."
                        },						
                        "params": {
                          "$ref": "#/paths/~1mnu_user(upd1)c.php/get/responses/200/content/application~1json/schema/items/params"
                        }
                      }
                    },
                    {
                      "$ref": "#/paths/~1logon.php/get/responses/200/content/application~1json/schema/items"
                    }
                  ]
                }			
              }
            }
          }
        }
      }
    },
    "/help.php": {
      "get": {
        "summary": "Help request",
        "description": "Request Help text from the Geoprise GM-X Auto ERP Application.",
        "operationId": "help",
        "parameters": [
          {
            "$ref": "#/components/parameters/session_name"	
          },
          {
            "$ref": "#/components/parameters/taskid"	
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response containing the Help text.",
            "content": {
              "text/html": {
                "schema": {
                  "type": "string",
                  "description": "The raw HTML content of the page containing the Help text"
                }
              }
            }
          }
        }		  
      } 
    } 
  },
  "components": {
    "schemas": {
      "callingTask": {
        "type": "object",	
        "description": "The task from which the popup task was called",		
        "examples": {			
          "type": "object",
          "required": [
            "alert",
            "actbar",
            "menubar",
            "params"
          ],
          "items": {
            "$ref": "./GMXAuto_asset.json#/paths/finance-fa~1asset(upd1).php/get/responses/200/content/application~1json/schema/items",
            "errmsg": {
              "line": {
                "enum": [
                  "Nothing selected from popup screen."           
                ]
              }
            }
          }
        }		
      },
      "choose": {
        "type": "string",			    
        "description": "instruction to return any selection (or multiple selections, if allowed) to previous form",
        "pattern": "^CHOOSE$"
      },
      "choosenull": {
        "type": "string",			    
        "description": "instruction to return no selections to previous form",
        "pattern": "^CHOOSE NULL$"
      },
      "clear": {
        "type": "string",			    
        "description": "instruction to remove all search criteria",
        "pattern": "^CLEAR$"
      },
      "collapse": {
        "type": "string",			    
        "description": "instruction to hide all the branches and leaves of the tree",
        "pattern": "^COLLAPSE$"
      },
      "copy": {
        "type": "string",			    
        "description": "instruction to copy the values of all form fields for pasting into a different instance of the same form",
        "pattern": "^COPY$"
      },	
      "created_date": {
        "type": "string",			    
        "description": "the date and time on which the record was created",
        "example": "04 Aug 2026 02:21:56"
      },
      "created_user": {
        "type": "string",			    
        "description": "the identity of the user which created the record",
        "example": "DLEE"
      },	
      "csrf_id": {
        "type": "string",			    
        "description": "unique request verification value for Cross-Site Request Forgery (CSRF) protection",
        "minLength": 23,
        "maxLength": 23,
        "pattern": "^[0-9a-fA-F]{14}\\.[0-9]{8}$"
      },
      "delete": {
        "type": "string",			    
        "description": "instruction to delete the record in the current form from the database",
        "pattern": "^DELETE$"
      },
      "error": {
        "type": "string",			    
        "description": "error encountered during validation of data submitted for a specific form field (if any)",
        "example": "column_id cannot be blank."
      },
      "errmsg": {
        "type": "string",			    
        "description": "error encountered during validation or processing of entire form (if any)",
        "example": "This action is not allowed."
      },
      "expand": {
        "type": "string",			    
        "description": "instruction to show all the branches and leaves of the tree",
        "pattern": "^EXPAND$"
      },
      "infomsg": {
        "type": "string",			    
        "description": "short description of successful processing outcome",
        "example": "The payment amount matches the document balances - payment is complete"
      },
      "InnerData": {
        "type": "object",
        "description": "A one-indexed collection of data for inner zone of the form. Keys begin with the column name, followed by a row number suffix enclosed in square braces (\"[\" and \"]\") which must be string representations of positive integers starting at \"1\". $ref: #/components/schema/Page/properties/numrows and $ref: #/components/schema/Page/properties/lastpage define the maximum row number from the following formula: maximum = IF (numrows / lastpage > 50 then 100 ELSE IF (numrows / lastpage > 25 then 50 ELSE IF (numrows / lastpage > 10 then 25 ELSE 10)))",
        "propertyNames": {
          "type": "string",
          "pattern": "^[a-z0-9_]{1,64}\\[(?:[1-9][0-9]?|100)\\]$"
        },    
        "additionalProperties": {
          "type": "string"
        },
        "example": {
          "document_reference[1]": "6654397LT9TBF5Q7F",		  
          "account_id[1]": "1.234.00",
          "debit_functional[1]": "998.72",
          "credit_functional[1]": "",
          "document_reference[2]": "6654397LT9TBF5Q7F",		  
          "account_id[2]": "2.421.02",
          "debit_functional[2]": "",
          "credit_functional[2]": "998.72"
        }
      },
      "InnerDataNoLimit": {
        "type": "object",
        "description": "A one-indexed collection of data for inner zone of the form. Keys begin with the column name, followed by a row number suffix enclosed in square braces (\"[\" and \"]\") which must be string representations of positive integers starting at \"1\".",
        "propertyNames": {
          "type": "string",
          "pattern": "^[a-z0-9_]{1,64}\\[[1-9][0-9]*\\]$"
        },    
        "additionalProperties": {
          "type": "string"
        },
        "example": {
          "sort_seq[1]": "2",		  
          "output_name[1]": "Order Id",
          "sort_seq[2]": "",		  
          "output_name[2]": "",
          "sort_seq[3]": "3",		  
          "output_name[3]": "Ship Country Id"
        }
      },
      "InnerTasks": {
        "type": "object",
        "description": "A one-indexed collection of popup tasks for inner zone of the form. Keys begin with the task ID (prefixed by \"#task#inner#\"), followed by a row number suffix enclosed in square braces (\"[\" and \"]\") which must be string representations of positive integers starting at \"1\". $ref: #/components/schema/Page/properties/numrows and $ref: #/components/schema/Page/properties/lastpage define the maximum row number from the following formula: maximum = IF (numrows / lastpage > 50 then 100 ELSE IF (numrows / lastpage > 25 then 50 ELSE IF (numrows / lastpage > 10 then 25 ELSE 10)))",
        "propertyNames": {
          "type": "string",
          "pattern": "^[a-z0-9_]{1,64}\\[(?:[1-9][0-9]?|100)\\]$"
        },    
        "additionalProperties": {
          "type": "string"
        },
        "example": {
          "task#inner#fgl_gl_account(popup4)[3]": "Choose GL Account"		  
        }
      },
      "Item": {
        "type": "object",
        "required": [
          "id",
          "curitem",		    
          "lastitem"
        ],
        "properties": {
          "id": {
            "type": "string",
            "example": "journal_entry_status_type"
          },
          "curitem": {
            "type": "integer",
            "description": "current scrolling item",
            "format": "int32",
            "minimum": 1,
            "example": "1"	
            },		    
          "lastitem": {
            "type": "integer",
            "description": "total number of rows returned by the query",
            "format": "int32",
            "minimum": 1,
            "example": "1"	
          }
        }		    
      },
      "LoggedInAs": {
        "type": "string",
        "description": "user name and last GET request timestamp, for desktop display",
        "example": "Derek Lee [04 Aug 2026 02:21:56 GMT -07:00]"		    
      },	
      "LoggedInAsName": {
        "type": "string",
         "description": "user name without last GET request timestamp, for mobile display",
        "example": "Derek Lee"		    
      },
      "LookupOption": {
        "type": "object",
        "required": [
          "key"
        ],
        "properties": {
          "key": {
            "type": "string",
            "description": "value within an option list",
            "example": {
              "": "null",
              "column_id": "Column Id"
            }
          }
        }	
      },
      "MenuBar": {
        "type": "object",
        "required": [
          "button",
          "stack"
        ],
        "properties": {
          "button": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id",
                "csrf_id"
              ],
              "properties": {
                "id": {
                  "type": "string",
                  "description": "task ID",
                  "example": "pro_product(list1)"
                },
                "csrf_id": {
                  "$ref": "#/components/schemas/csrf_id"
                },
                "active": {
                  "type": "string",
                  "description": "indicates if the menu button can currently be used to send a GET request to the GM-X server",				
                  "example": "y"
                }
              }
            }
          },
          "stack": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id"
              ],
              "properties": {
                "id": {
                  "type": "string",
                  "description": "task ID",				
                  "example": "business_processes"
                },
                "csrf_id": {
                  "$ref": "#/components/schemas/csrf_id"
                },
                "active": {
                  "type": "string",
                  "description": "indicates if the breadcrumb link can currently be used to send a GET request to the GM-X server",					
                  "example": "y"
                }
              }
            }
          }
        }
      },	
      "NavBar": {
          "type": "object",
          "required": [
            "button"
          ],
          "properties": {
            "button": {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "id",
                  "context_preselect",			    
                  "tooltip"
                ],
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "'task#', followed by zone ID, followed by '#', followed by task ID",
                    "example": "task#main#pro_product(upd1)"
                  },
                  "context_preselect": {
                    "type": "string",
                    "description": "indicates if an item must be selected from the list (Y) before activating the button, or not (N)",				
                    "enum": [
                      "N",
                      "Y"
                    ]
                  },
                  "tooltip": {
                    "type": "string",
                    "description": "task name",				
                    "example": "Update Product"
                  }
                }
              }
            }
          }
      },
      "order": {
        "type": "string",
        "description": "record sorting sequence (ascending or descending)",
        "enum": [
          "asc",
          "desc"					    
        ]		    
      },
      "OuterData": {
        "type": "object",
        "description": "A one-indexed collection of data for outer zone of the form. Keys prefixed by \"__outer__\", followed by the column name",
        "propertyNames": {
          "type": "string",
          "pattern": "^__outer__[a-z0-9_]{0,64}$"
        },    
        "additionalProperties": {
          "type": "string"
        },
        "example": {
          "__outer__transaction_date": "24 Aug 2026",		  
          "__outer__journal_desc": "Subsidiary expenses paid by corporate parent",
          "__outer__uom_id_statistic": ""
        }
      },	  
      "Page": {
        "type": "object",
        "required": [
          "id",
          "numrows",
          "curpage",		    
          "lastpage"
        ],
        "properties": {
          "id": {
            "type": "string",
            "enum": [
              "inner",
              "link",
              "main",
              "middle",
              "middle1",
              "middle2",
              "mnu_todo",
              "outer",
              "workitem_role",
              "workitem_user"
            ],
            "example": "main"
          },
          "numrows": {
            "type": "integer",
            "description": "total number of rows returned by the query",
            "format": "int32",
            "minimum": 0,
            "example": "68"			
          },
          "curpage": {
            "type": "integer",
            "description": "total number of rows returned by the query",
            "format": "int32",
            "minimum": 0,
            "example": "1"	
          },		    
          "lastpage": {
            "type": "integer",
            "description": "total number of pages returned by the query (at maximum of 10, 25, 50, or 100 rows per page)",
            "format": "int32",
            "minimum": 0,
            "example": "7"	
          }
        }		    
      },
      "PaginationWidth": {
        "type": "integer",
        "description": "defines how the pagination area is displayed; default display if zero, Google style display otherwise",
        "format": "int32",
        "minimum": 0,
        "example": "7"		    
      },
      "paste": {
        "type": "string",			    
        "description": "instruction to paste the values of all form fields copied from a different instance of the same form; required when values of form fields have been copied from a different instance",
        "pattern": "^Paste$"
      },
      "ProjectCode": {
        "type": "string",
        "description": "customisation project code for this server instance",
        "example": "gmx"			
      },
      "quicksearch": {
        "type": "string",			    
        "description": "instruction to query the records using the quicksearch criterion, and then re-display current form",
        "pattern": "^Quick Search$"
      },
      "QuicksearchOption": {
        "type": "object",
        "required": [
          "key"
        ],
        "properties": {
          "key": {
            "type": "string",
            "description": "column available for quicksearch criterion",
            "example": {
              "": "null",
              "column_id": "Column Id"
            }
          }
        }	
      },
      "quicksearch_field": {
        "type": "string",			    
        "description": "column for quicksearch criterion",
        "option": [
          {
            "$ref": "#components/schemas/QuicksearchOption"
          }					  
         ]
      },
      "quicksearch_value": {
        "type": "string",			    
        "description": "quicksearch criterion",		  
        "maxLength": 20,
        "pattern": "^.{0,20}$"
      },	  
      "quitCancel": {
        "type": "string",			    
        "description": "instruction to return to previous form",
        "pattern": "^CANCEL$"
      },
      "quitClose": {
        "type": "string",			    
        "description": "instruction to return to previous form",
        "pattern": "^CLOSE$"
      },
      "rdc_selection_lock": {
        "type": "integer",
        "description": "instruction to lock selected record(s) to re-select them automatically when returning to current form",
        "format": "int32",
        "minimum": 0,
        "maximum": 1,	    
        "example": "0",
        "default": 0
      },
      "reset": {
        "type": "string",			    
        "description": "instruction to remove all search criteria, sorting, and page settings, and then re-display current form",
        "pattern": "^RESET$"
      },	  
      "revised_date": {
        "type": "string",			    
        "description": "the date and time on which the record was last updated",
        "example": "04 Aug 2026 02:21:56"
      },
      "revised_user": {
        "type": "string",			    
        "description": "the identity of the user which last updated the record",
        "example": "DLEE"
      },
      "ScriptURL": {
        "type": "string",
        "description": "concatenation of URL followed by path"
      },	    
      "ScrollingWidth": {
        "type": "integer",
        "description": "defines how the scrolling area is displayed; default display if zero, Google style display otherwise",
        "format": "int32",
        "minimum": 0,
        "example": "5"			    
      },
      "select": {
        "type": "object",
        "description": "A sparse, one-indexed collection indicating selected rows on the form. Keys do not need to be sequential but must be string representations of positive integers starting at \"1\". $ref: #/components/schema/Page/properties/numrows and $ref: #/components/schema/Page/properties/lastpage define the maximum collection size from the following formula: maximum = IF (numrows / lastpage > 50 then 100 ELSE IF (numrows / lastpage > 25 then 50 ELSE IF (numrows / lastpage > 10 then 25 ELSE 10)))",
        "propertyNames": {
          "pattern": "^[1-9][0-9]*$",
          "minimum": "1",
          "maximum": {
            "oneOf": [
              "10",		
              "25",				    
              "50",
              "100"
            ]			
          }
        },    
        "additionalProperties": {
          "type": "string",
          "enum": [
            "on"
          ]
        },
        "example": {
          "1": "on",
          "3": "on",
          "19": "on",
          "47": "on",
          "78": "on"
        }
      },
      "selectNoLimit": {
        "type": "object",
        "description": "A sparse, one-indexed collection indicating selected rows on the form. Keys do not need to be sequential but must be string representations of positive integers starting at \"1\".",
        "propertyNames": {
          "pattern": "^[1-9][0-9]*$",
          "minimum": "1"
        },    
        "additionalProperties": {
          "type": "string",
          "enum": [
            "on"
          ]
        },
        "example": {
          "1": "on",
          "3": "on",
          "19": "on",
          "47": "on",
          "78": "on"
        }
      },
      "selectOne": {
        "type": "string",
        "description": "Indicates the row selected from a popup form that allows only one row to be selected. The selected row number must be a string representation of a positive integer starting at \"1\". $ref: #/components/schema/Page/properties/numrows and $ref: #/components/schema/Page/properties/lastpage define the maximum allowable value from the following formula: maximum = IF (numrows / lastpage > 50 then 100 ELSE IF (numrows / lastpage > 25 then 50 ELSE IF (numrows / lastpage > 10 then 25 ELSE 10)))",
        "propertyNames": {
          "pattern": "^[1-9][0-9]*$",
          "minimum": "1",
          "maximum": {
            "oneOf": [
              "10",		
              "25",				    
              "50",
              "100"
            ]			
          }
        },    
        "example": [
          "1",
          "3",
          "19",
          "47",
          "78"
        ]
      },
      "session_name": {
        "type": "string",			    
        "description": "Name of session cookie set by GM-X application server after successful Internal, RADIUS, LDAP, or SSL authentication.",
        "minLength": 5,
        "maxLength": 6,
        "pattern": "^menu\\d{1,2}$"							
      },
      "submitBtn": {
        "type": "string",			    
        "description": "instruction to process the form and then return to previous form if successful, or re-display current form with error message(s) if unsuccessful",
        "pattern": "^SUBMIT$"
      },
      "submitnext": {
        "type": "string",			    
        "description": "instruction to process the form and then scroll to next form (or return to previous form if current form is the last in scrolling sequence) if successful, or re-display current form with error message(s) if unsuccessful",
        "pattern": "^SUBMIT+next$"
      },
      "submitstay": {
        "type": "string",			    
        "description": "instruction to process the form and then display a fresh copy of this form if successful, or re-display current form with error message(s) if unsuccessful",
        "pattern": "^SUBMIT+stay$"
      },
      "taskid": {
        "type": "string",			    
        "description": "Task associated with request.",
        "maxLength": 80,
        "pattern": "^[a-z_()]{1,80}$"							
      }	
    },
    "parameters": {
      "action": {
        "name": "action",
        "in": "query",
        "description": "instruction to log off, create a new session, or select/unselect all rows of the current page returned by the query (at maximum of 10, 25, 50, or 100 rows per page)",
        "schema": {
          "type": "string",
          "enum": [
	        "logout",	
	        "logout_all",
	        "newsession",		    
	        "selectall",
            "unselectall"
          ]
        }		    
      },
      "collapsed": {
        "name": "collapsed",
        "in": "query",
        "description": "unique identity of a specific tree view node to be collapsed so its branches and leaves are hidden",
        "schema": {
          "type": "string",
          "pattern": "^(.+)#\\1$"
        }		    
      },
      "csrf_id": {
        "name": "csrf_id",
        "in": "query",
        "description": "unique request verification value for Cross-Site Request Forgery (CSRF) protection; required for GET requests using different path",
        "required": true,	    
        "schema": {
          "type": "string",
          "minLength": 23,
          "maxLength": 23,
          "pattern": "^[0-9a-fA-F]{14}\\.[0-9]{8}$"
        }		    
      },
      "expand": {
        "name": "expand",
        "in": "query",
        "description": "unique identity of a specific tree view node to be expanded so its branches and leaves are visible",
        "schema": {
          "type": "string",
          "pattern": "^(.+)#\\1$"
        }		    
      },
      "item": {
        "name": "item",
        "in": "query",
        "description": "instruction to return a specific row returned by a query; required when scrolling parameter exists",
        "schema": {
          "type": "integer",
          "format": "int32",		    
          "minimum": "1",
          "maximum": {
            "$ref": "#/components/schemas/Item/properties/lastitem"	
          }
        }		    
      },	
      "page": {
        "name": "page",
        "in": "query",
        "description": "instruction to return a specific page of the rows returned by a query; required when pagination parameter exists",
        "schema": {
          "type": "integer",
          "format": "int32",		    
          "minimum": "1",
          "maximum": {
            "$ref": "#/components/schemas/Page/properties/lastpage"	
          }
        }		    
      },
      "pagesize": {
        "name": "pagesize",
        "in": "query",
        "description": "instruction to return a maximum of 10, 25, 50, or 100 rows per page",
        "schema": {
          "type": "integer",
          "format": "int32",
          "enum": [
            "10",
            "25",
            "50",			
            "100"
          ],
          "maximum": {
            "$ref": "#/components/schemas/Page/properties/numrows"				    
          }		    
        }		    
      },
      "pagination": {
        "name": "pagination",
        "in": "query",
        "description": "applicable zone for a pagination request (e.g. main, outer, inner, middle, middle1, middle2, link); required when page parameter exists",
        "schema": {
          "type": "string",			
          "enum": [
            {
              "$ref": "#/components/schemas/Page/properties/id"
            }
          ]		    
        }		    
      },
      "scrolling": {
        "name": "scrolling",
        "in": "query",
        "description": "applicable class for a scrolling request; required when scrolling parameter exists",
        "schema": {
          "type": "string",
          "maxLength": 64,		
          "enum": [
            {
              "$ref": "#/components/schemas/Item/properties/id"
            }
          ]		    
        }		    
      },
      "selection": {
        "name": "selection",
        "in": "query",
        "description": "task ID selection from menu bar",
        "schema": {
          "type": "string",
          "enum": [
            {
              "$ref": "#/components/schemas/Item/properties/taskid"
            }
          ]		    
        }		    
      },
      "session_name": {
        "name": "session_name",
        "in": "query",
        "description": "Name of session cookie set by GM-X application server after successful Internal, RADIUS, LDAP, or SSL authentication.",
        "required": true,
        "schema" : {
          "type": "string",
          "minLength": 5,
          "maxLength": 6,
          "pattern": "^menu\\d{1,2}$"
        }		    
      }, 
      "taskid": {
        "name": "taskid",
        "in": "query",
        "description": "task associated with request; required when accessing written help",
        "schema": {
          "type": "string",			
          "maxLength": 80,
          "enum": [
            {
              "$ref": "#/components/schemas/taskid"
            }
          ]		
        }		    
      }
    },
    "securitySchemes": {
      "AWSELBAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": "AWSELBAuthSessionCookie-0",
        "description": "The AWS ALB authentication session cookie. If its size is greater than 4K, and less than 11K, the load balancer shards it into multiple cookies (AWSELBAuthSessionCookie-0, AWSELBAuthSessionCookie-1, etc.)."		
      },		
      "sessionAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": {
          "schema" : {
            "type": "string",
            "minLength": 22,
            "maxLength": 256,
            "pattern": "^menu\\d{1,2}=(?:[A-Za-z0-9]{22,128}|[0-9a-fA-F]{22,256})$"
          }		
        },
        "description": "The PHP session cookie set by GM-X application server after successful Internal, RADIUS, LDAP, or SSL authentication."
      }
    }	
  },
  "security": [
    "AWSELBAuth": {
      "$ref": "#/components/securitySchemes/AWSELBAuth"
    },	  
    "sessionAuth": {
      "$ref": "#/components/securitySchemes/sessionAuth"
    },
    "antiCSRFToken": {
      "$ref": "#/components/parameters/csrf_id"
    }	
  ]
}